### ISSUE TITLE
Reporter

### ISSUE THREAD

**Issue by brunohhomem** [bioinformatist/LncPipeReporter#10]
Hi, 
I'm running lncpipe, and the a error always show up when the lncpipeReporter process is running.

The error message is: 
"processing file: reporter.Rmd Quitting from lines 51-99 (reporter.Rmd) Error in `[.data.table`(x, , 2) : Item 1 of j is 2 which is outside the column number range [1,ncol=1] Calls: run_report ... FUN -> determine type -> paste -> [ -> [.data.table Execution halted"
I'm using docker, lastest nextflow and lncpipe versions. I'm not a developer, could someone help me?

**Comment by likelet** [comment]
@bioinformatist can you have a check here?

**Comment by bioinformatist** [comment]
@brunohhomem Can you provide us files for reproducing this matter?

**Comment by bioinformatist** [comment]
Closed for no reply.
