### ISSUE TITLE
Install error on Ubuntu linux system

### ISSUE THREAD

**Issue by yzh37545** [bioinformatist/LncPipeReporter#9]
Hi, I meet an error showed like this ; 

Installing 116 packages: acepack, annotate, AnnotationDbi, base64enc, BH, Biobase, BiocGenerics, BiocParallel, bit, bit64, bitops, blob, caTools, checkmate, colorspace, cowplot, crosstalk, data.table, DBI, DelayedArray, dendextend, DEoptimR, DESeq2, diptest, dplyr, DT, edgeR, evaluate, fansi, flexdashboard, flexmix, foreach, formatR, Formula, fpc, futile.logger, futile.options, gclus, gdata, genefilter, geneplotter, GenomeInfoDb, GenomeInfoDbData, GenomicRanges, ggplot2, ggsci, gplots, gridExtra, gtable, gtools, heatmaply, hexbin, highr, Hmisc, htmlTable, htmltools, htmlwidgets, httpuv, IRanges, iterators, kernlab, knitr, labeling, lambda.r, later, latticeExtra, lazyeval, limma, locfit, markdown, matrixStats, mclust, modeltools, munsell, mvtnorm, NOISeq, pillar, pkgconfig, plogr, plotly, plyr, prabclus, promises, qap, RColorBrewer, RcppArmadillo, RCurl, registry, reshape2, rmarkdown, robustbase, RSQLite, S4Vectors, scales, seriation, shiny, snow, sourcetools, stringi, stringr, SummarizedExperiment, tibble, tidyr, tidyselect, tinytex, trimcluster, TSP, utf8, viridis, viridisLite, webshot, xfun, XML, xtable, XVector, zlibbioc
Error in if (type == "binary") { : argument is of length zero
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
In addition: Warning message:
In is.na(remote_deps$package) :
  is.na() applied to non-(list or vector) of type 'NULL'
Execution halted

I found in some discussion. Developers mentioned that the reason is that the pkgtype is not defined. Is there any clue I could fix it?

Thank you!

**Comment by bioinformatist** [comment]
Hi,
Can you provide me the command you used during installation?

**Comment by bioinformatist** [comment]
Closed for no reply.
